FROM jenkins/jenkins:2.89.4-slim

LABEL maintainer="mark.earl.waite@gmail.com"

USER root

RUN apt-get clean && apt-get update && apt-get install -y \
  build-essential \
  gcc-multilib \
  gnupg \
  graphviz \
  lsb-release \
  make \
  procps \
  && rm -rf /var/lib/apt/lists/*

# Install git lfs extension
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated --no-install-recommends git-lfs && \
    git lfs install && \
    rm -r /var/lib/apt/lists/*

# Disable assistive technologies since openjdk:slim installs headless JDK
RUN sed -i 's/assistive_technologies=.*/assistive_technologies=/g' /etc/java-8-openjdk/accessibility.properties

USER jenkins

# `/usr/share/jenkins/ref/` contains all reference configuration we want
# to set on a fresh new installation. Use it to bundle additional plugins
# or config file with your custom jenkins Docker image.
ADD ref /usr/share/jenkins/ref/
